version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php 
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
